# Build the GCP Marketplace image for NGINX+ Ingress Controller deployer and
# tester variants, pushing them to F5's gcr.io repo.
---
steps:
  # Warm up docker cache
  - id: pull-busybox
    name: docker
    entrypoint: sh
    args:
      - -c
      - "docker pull busybox:${_BUSYBOX_TAG} || exit 0"
    waitFor:
      - '-'
  - id: pull-gcrane
    name: docker
    entrypoint: sh
    args:
      - -c
      - "docker pull gcr.io/go-containerregistry/gcrane:${_GCRANE_TAG} || exit 0"
    waitFor:
      - '-'
  # Install JQ binary to a known path
  - id: download-jq
    name: busybox:${_BUSYBOX_TAG}
    entrypoint: /bin/sh
    args:
      - -c
      - >-
        mkdir -p /workspace/bin &&
          wget -q -O /workspace/bin/jq https://github.com/stedolan/jq/releases/download/jq-${_JQ_VERSION}/jq-linux64 &&
          chmod 0755 /workspace/bin/jq
    waitFor:
      - pull-busybox
  # Use JQ to extract the NGINX+ JWT from JSON secret and configure Docker login
  # to NGINX private repository; gcrane groks Docker login config.
  - id: extract-nginx-creds
    name: docker
    entrypoint: /bin/sh
    args:
      - -c
      - >-
        echo none | docker login --username $(/workspace/bin/jq -nr 'env.NGINX_SECRET | fromjson | .jwt') --password-stdin private-registry.nginx.com &&
          rm -f /workspace/bin/jq
    secretEnv:
      - NGINX_SECRET
    waitFor:
      - download-jq
  # Build NGINX+ Ingress Controller deployer and tester
  - id: build-kic-deployer
    name: docker
    args:
      - build
      - --file
      - Dockerfile
      - --build-arg
      - REGISTRY=${_REGISTRY}
      - --build-arg
      - TAG=${_VERSION}
      - --tag
      - ${_REGISTRY}/${_BASE_NAME}/deployer:${_VERSION}
      - --tag
      - ${_REGISTRY}/${_BASE_NAME}/deployer:${_RELEASE_TRACK}
      - .
    dir: nginx-ingress-plus
    waitFor:
      - '-'
  - id: build-kic-apptest
    name: docker
    args:
      - build
      - --file
      - apptest/Dockerfile
      - --tag
      - ${_REGISTRY}/${_BASE_NAME}/tester:${_VERSION}
      - --tag
      - ${_REGISTRY}/${_BASE_NAME}/tester:${_RELEASE_TRACK}
      - apptest
    dir: nginx-ingress-plus
    waitFor:
      - '-'
  # Build NGINX+ Ingress Controller w/NGINX App Protect WAF deployer and tester
  - id: build-kic-nap-deployer
    name: docker
    args:
      - build
      - --file
      - Dockerfile
      - --build-arg
      - REGISTRY=${_REGISTRY}
      - --build-arg
      - TAG=${_VERSION}
      - --tag
      - ${_REGISTRY}/${_BASE_NAME}-nap/deployer:${_VERSION}
      - --tag
      - ${_REGISTRY}/${_BASE_NAME}-nap/deployer:${_RELEASE_TRACK}
      - .
    dir: nginx-ingress-plus-nap
    waitFor:
      - '-'
  - id: build-kic-nap-apptest
    name: docker
    args:
      - build
      - --file
      - apptest/Dockerfile
      - --tag
      - ${_REGISTRY}/${_BASE_NAME}-nap/tester:${_VERSION}
      - --tag
      - ${_REGISTRY}/${_BASE_NAME}-nap/tester:${_RELEASE_TRACK}
      - apptest
    dir: nginx-ingress-plus-nap
    waitFor:
      - '-'
  # Build NGINX+ Ingress Controller w/NGINX App Protect DoS deployer and tester
  # NOTE: the container build steps depend on successful copy of NGINX Inc
  # App Protect Dos Arbitrator container to gcr.io with the correct tags.
  - id: copy-kic-dos-arbitrator-ver
    name: gcr.io/go-containerregistry/gcrane:${_GCRANE_TAG}
    args:
      - cp
      - --platform
      - linux/amd64
      - ${_NAP_DOS_ARBITRATOR_IMAGE}:${_NAP_DOS_ARBITRATOR_TAG}
      - ${_REGISTRY}/${_BASE_NAME}-dos/nap-dos-arbitrator:${_VERSION}
    waitFor:
      - pull-gcrane
  - id: copy-kic-dos-arbitrator-rel
    name: gcr.io/go-containerregistry/gcrane:${_GCRANE_TAG}
    args:
      - cp
      - --platform
      - linux/amd64
      - ${_NAP_DOS_ARBITRATOR_IMAGE}:${_NAP_DOS_ARBITRATOR_TAG}
      - ${_REGISTRY}/${_BASE_NAME}-dos/nap-dos-arbitrator:${_RELEASE_TRACK}
    waitFor:
      - pull-gcrane
  - id: build-kic-dos-deployer
    name: docker
    args:
      - build
      - --file
      - Dockerfile
      - --build-arg
      - REGISTRY=${_REGISTRY}
      - --build-arg
      - TAG=${_VERSION}
      - --tag
      - ${_REGISTRY}/${_BASE_NAME}-dos/deployer:${_VERSION}
      - --tag
      - ${_REGISTRY}/${_BASE_NAME}-dos/deployer:${_RELEASE_TRACK}
      - .
    dir: nginx-ingress-plus-dos
    waitFor:
      - copy-kic-dos-arbitrator-ver
      - copy-kic-dos-arbitrator-rel
  - id: build-kic-dos-apptest
    name: docker
    args:
      - build
      - --file
      - apptest/Dockerfile
      - --tag
      - ${_REGISTRY}/${_BASE_NAME}-dos/tester:${_VERSION}
      - --tag
      - ${_REGISTRY}/${_BASE_NAME}-dos/tester:${_RELEASE_TRACK}
      - apptest
    dir: nginx-ingress-plus-dos
    waitFor:
      - copy-kic-dos-arbitrator-ver
      - copy-kic-dos-arbitrator-rel
  # Build NGINX+ Ingress Controller w/NGINX App Protect WAF & DoS deployer and
  # tester
  # NOTE: the container build steps depend on successful copy of NGINX Inc
  # App Protect Dos Arbitrator container to gcr.io with the correct tags.
  - id: copy-kic-nap-dos-arbitrator-ver
    name: gcr.io/go-containerregistry/gcrane:${_GCRANE_TAG}
    args:
      - cp
      - --platform
      - linux/amd64
      - ${_NAP_DOS_ARBITRATOR_IMAGE}:${_NAP_DOS_ARBITRATOR_TAG}
      - ${_REGISTRY}/${_BASE_NAME}-nap-dos/nap-dos-arbitrator:${_VERSION}
    waitFor:
      - pull-gcrane
  - id: copy-kic-nap-dos-arbitrator-rel
    name: gcr.io/go-containerregistry/gcrane:${_GCRANE_TAG}
    args:
      - cp
      - --platform
      - linux/amd64
      - ${_NAP_DOS_ARBITRATOR_IMAGE}:${_NAP_DOS_ARBITRATOR_TAG}
      - ${_REGISTRY}/${_BASE_NAME}-nap-dos/nap-dos-arbitrator:${_RELEASE_TRACK}
    waitFor:
      - pull-gcrane
  - id: build-kic-nap-dos-deployer
    name: docker
    args:
      - build
      - --file
      - Dockerfile
      - --build-arg
      - REGISTRY=${_REGISTRY}
      - --build-arg
      - TAG=${_VERSION}
      - --tag
      - ${_REGISTRY}/${_BASE_NAME}-nap-dos/deployer:${_VERSION}
      - --tag
      - ${_REGISTRY}/${_BASE_NAME}-nap-dos/deployer:${_RELEASE_TRACK}
      - .
    dir: nginx-ingress-plus-nap-dos
    waitFor:
      - copy-kic-nap-dos-arbitrator-ver
      - copy-kic-nap-dos-arbitrator-rel
  - id: build-kic-nap-dos-apptest
    name: docker
    args:
      - build
      - --file
      - apptest/Dockerfile
      - --tag
      - ${_REGISTRY}/${_BASE_NAME}-nap-dos/tester:${_VERSION}
      - --tag
      - ${_REGISTRY}/${_BASE_NAME}-nap-dos/tester:${_RELEASE_TRACK}
      - apptest
    dir: nginx-ingress-plus-nap-dos
    waitFor:
      - copy-kic-nap-dos-arbitrator-ver
      - copy-kic-nap-dos-arbitrator-rel
timeout: 1200s
options:
  env:
    - DOCKER_BUILDKIT=1
  dynamic_substitutions: true
  substitution_option: 'ALLOW_LOOSE'
images:
  - ${_REGISTRY}/${_BASE_NAME}/deployer:${_VERSION}
  - ${_REGISTRY}/${_BASE_NAME}/deployer:${_RELEASE_TRACK}
  - ${_REGISTRY}/${_BASE_NAME}/tester:${_VERSION}
  - ${_REGISTRY}/${_BASE_NAME}/tester:${_RELEASE_TRACK}
  - ${_REGISTRY}/${_BASE_NAME}-nap/deployer:${_VERSION}
  - ${_REGISTRY}/${_BASE_NAME}-nap/deployer:${_RELEASE_TRACK}
  - ${_REGISTRY}/${_BASE_NAME}-nap/tester:${_VERSION}
  - ${_REGISTRY}/${_BASE_NAME}-nap/tester:${_RELEASE_TRACK}
  - ${_REGISTRY}/${_BASE_NAME}-dos/deployer:${_VERSION}
  - ${_REGISTRY}/${_BASE_NAME}-dos/deployer:${_RELEASE_TRACK}
  - ${_REGISTRY}/${_BASE_NAME}-dos/tester:${_VERSION}
  - ${_REGISTRY}/${_BASE_NAME}-dos/tester:${_RELEASE_TRACK}
  - ${_REGISTRY}/${_BASE_NAME}-nap-dos/deployer:${_VERSION}
  - ${_REGISTRY}/${_BASE_NAME}-nap-dos/deployer:${_RELEASE_TRACK}
  - ${_REGISTRY}/${_BASE_NAME}-nap-dos/tester:${_VERSION}
  - ${_REGISTRY}/${_BASE_NAME}-nap-dos/tester:${_RELEASE_TRACK}
availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_NUMBER/secrets/${_NGINX_REPO_AUTH_KEY}/versions/${_NGINX_REPO_AUTH_VERSION}"
      env: NGINX_SECRET
substitutions:
  # The Container Registry/Artifact Repository where the images will be pushed
  _REGISTRY: 'gcr.io/f5-7626-networks-public/nginxinc'
  # Base product name for NGINX Ingress Controller line
  _BASE_NAME: nginx-ingress-plus
  # Published NGINX App Protect DoS Arbitrator container image and tag to use
  _NAP_DOS_ARBITRATOR_IMAGE: docker-registry.nginx.com/nap-dos/app_protect_dos_arb
  _NAP_DOS_ARBITRATOR_TAG: '1.1.0'
  # Busybox tag to use
  _BUSYBOX_TAG: '1.36.0'
  # gcrane tag to use
  _GCRANE_TAG: latest
  # JQ version to install
  _JQ_VERSION: '1.6'
  # NGINX+ secret key containing certificate and key fields - REQUIRED
  _NGINX_REPO_AUTH_KEY: ''
  _NGINX_REPO_AUTH_VERSION: 'latest'
  ## Dynamic substitutions; strip the leading v from git tag for version and
  ## generate the release track as major.minor only
  _VERSION: '${TAG_NAME#v}'
  _RELEASE_TRACK: '${_VERSION%.*}'
