# spell-checker: disable
---
testerImagePullPolicy: Always
gcpReportingSecret: placeholder
ubbAgentImage: placeholder
nginx-ingress:
  rbac:
    create: false
  controller:
    nginxplus: true
    appprotect:
      enable: false
    appprotectdos:
      enable: false
    image:
      pullPolicy: Always
    extraContainers:
      - name: ubbsidecar
        image: placeholder
        imagePullPolicy: Always
        env:
          - name: AGENT_ENCODED_KEY
            valueFrom:
              secretKeyRef:
                name: placeholder
                key: reporting-key
          - name: AGENT_CONSUMER_ID
            valueFrom:
              secretKeyRef:
                name: placeholder
                key: consumer-id
