# yamllint disable rule:line-length
---
properties:
  testerImage:
    type: string
    default: gcr.io/f5-7626-networks-public/memes/nginx-ic/nginx-plus-ingress/tester:3.0.1
    x-google-property:
      type: IMAGE
